import { generateObject } from "ai";
import { google } from "@ai-sdk/google";
import { z } from "zod";
import type { TopicDocument } from "@aethon/content-core";

/**
 * Zod schema for a single quiz question generated by the AI engine.
 */
export const quizQuestionSchema = z.object({
    id: z.string(),
    prompt: z.string(),
    options: z.array(z.string()),
    correctIndex: z.number().int(),
    explanation: z.string(),
    conceptKey: z.string(),
    hint: z.string().optional(),
});

/**
 * QuizQuestion interface derived from the Zod schema.
 */
export type QuizQuestion = z.infer<typeof quizQuestionSchema>;

export interface GenerateQuizOptions {
    topic: TopicDocument;
    questionCount: number;
    includeHints?: boolean;
}

/**
 * Builds the prompt for quiz generation based on topic content and options.
 */
function buildQuizPrompt(topic: TopicDocument, questionCount: number, includeHints: boolean): string {
    const hintInstruction = includeHints
        ? "Include a 'hint' field for each question that gives the learner a subtle clue without revealing the answer."
        : "Do NOT include a 'hint' field in the output.";

    return `You are an expert educator creating quiz questions for a developer learning platform.

Topic: ${topic.metadata.title}
Description: ${topic.metadata.description}
Difficulty: ${topic.metadata.difficulty}

Topic Content:
${topic.body}

Generate exactly ${questionCount} multiple-choice quiz questions that test understanding of this topic.

Requirements:
- Each question must have exactly 4 options
- The correctIndex must be a valid index (0-3) pointing to the correct option
- The explanation should clearly explain why the correct answer is right
- The conceptKey should be a short kebab-case identifier for the concept being tested (e.g., "closure-scope", "event-loop")
- Each question id should be a unique string like "q1", "q2", etc.
- Questions should cover different aspects of the topic
- ${hintInstruction}`;
}

/**
 * Generates quiz questions for a given topic using the Vercel AI SDK.
 *
 * Uses `generateObject` with a Zod schema for structured output.
 * Retries once on malformed response; throws a descriptive error on second failure.
 */
export async function generateQuiz(options: GenerateQuizOptions): Promise<QuizQuestion[]> {
    const { topic, questionCount, includeHints = false } = options;

    const schema = z.object({
        questions: z.array(
            includeHints
                ? quizQuestionSchema
                : quizQuestionSchema.omit({ hint: true })
        ),
    });

    const prompt = buildQuizPrompt(topic, questionCount, includeHints);
    const model = google("gemini-2.5-flash");

    let lastError: unknown;

    for (let attempt = 0; attempt < 2; attempt++) {
        try {
            const { object } = await generateObject({
                model,
                schema,
                prompt,
            });

            return object.questions as QuizQuestion[];
        } catch (error) {
            lastError = error;

            // Only retry once — if this was the first attempt, continue to retry
            if (attempt === 0) {
                continue;
            }
        }
    }

    throw new Error(
        `Quiz generation failed after 2 attempts for topic "${topic.metadata.title}". ` +
        `Last error: ${lastError instanceof Error ? lastError.message : String(lastError)}`
    );
}
