packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

catalog:
  '@prisma/client': ^7.7.0
  '@trpc/client': ^11.16.0
  '@trpc/server': ^11.16.0
  '@types/express': ^5.0.1
  '@types/react': ^19.2.10
  '@types/react-dom': ^19.2.3
  ai: ^6.0.3
  better-auth: 1.6.9
  dotenv: ^17.2.2
  lucide-react: 0.546.0
  next-themes: 0.4.6
  react: ^19.2.3
  react-dom: ^19.2.3
  sonner: 2.0.7
  tailwindcss: ^4.1.18
  typescript: ^6
  zod: ^4.1.13
